### ISSUE TITLE
custom_jails are not populating the 'ignoreip" values in the custom_jail.conf.epp template

### ISSUE THREAD

**Issue by dwest-galois** [voxpupuli/puppet-fail2ban#108]
I am pretty sure this is just a matter of fixing a syntax typo.  

`ignoreip = <% $ignoreip.join(' ') -%>`

should be

`ignoreip = <%= $ignoreip.join(' ') -%>`

This change "Inserts the value of a single expression" instead of just executing it.

https://github.com/voxpupuli/puppet-fail2ban/blob/bfc03b8443ca0df47a4e1a59e007b8ae99727a59/templates/common/custom_jail.conf.epp#L25

**Comment by bastelfreak** [comment]
thanks for reporting this bug. Are you able to provide a pull request with a fix?
