### ISSUE TITLE
Update puppet forge

### ISSUE THREAD

**Issue by ftwrobert** [voxpupuli/puppet-fail2ban#116]
This isn't so much an issue, but, I'm hoping someone can update puppet forge with an updated version of puppet-fail2ban.

Personally, I'm looking for bionic support.

I also realize there are other ways of adding this module to my project.

Thanks for your time!

**Comment by alexjfisher** [comment]
I think #132 should be resolved first.  Can anyone volunteer to create a PR for that?

**Comment by neomilium** [comment]
@alexjfisher I'm working on it, and started the work by #134

**Comment by dhoppe** [comment]
I will add support for CentOS 8 / RedHat 8 and after that we should do a release.
