### ISSUE TITLE
Option to disable service start/stop notifications

### ISSUE THREAD

**Issue by deric** [voxpupuli/puppet-fail2ban#143]
Service start/stop notifications are generating too many emails. I don't want to disable email notifications completely, but only on these actions.

Probably the [best approach](https://serverfault.com/a/658559/65750) seems to be overriding `actionstart` and `actionstop` defined in `/etc/fail2ban/action.d/sendmail-common.conf` with another config `/etc/fail2ban/action.d/sendmail-common.local`:

```
# Override the Fail2Ban defaults in sendmail-common.conf with these entries
[Definition]
# Disable email notifications of jails stopping or starting
actionstart =
actionstop =
```
Or is there some better way supported by this module?

**Comment by dhoppe** [comment]
As far as I know, this module does not support this feature. But you should take a look at ```config_file_hash``` which allows you to deploy your own files / templates. For example: 
```puppet
class { 'fail2ban':
  config_file_hash => {
    'sendmail-common.local' => {
      config_file_path   => '/etc/fail2ban/action.d/sendmail-common.local',
      config_file_source => 'puppet:///modules/profile/fail2ban/etc/fail2ban/action.d/sendmail-common.local',
    }
  }
}
```
