### ISSUE TITLE
Add Ubuntu 22.04 Template

### ISSUE THREAD

**Issue by NickStallman** [voxpupuli/puppet-fail2ban#182]
## What are you seeing

Ubuntu 22.04 does not currently have any template. This should be pretty straightfroward and 20.04's template would likely work fine.

## Output log
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/Ubuntu/22.04/etc/fail2ban/jail.conf.epp' (file: /etc/puppetlabs/code/environments/production/modules/fail2ban/manifests/init.pp, line: 51, column: 26) on node xxx.com
```

**Comment by ahoiroman** [comment]
Same here. Would be nice to see an update as 22.04 is LTS.

**Comment by maxadamo** [comment]
the fix is released (and you can see it in the main branch). 
Please stay tuned. I'm trying to create the release

**Comment by maxadamo** [comment]
fixed by https://github.com/voxpupuli/puppet-fail2ban/pull/186

**Comment by informaticavera** [comment]
Thanks, when will it be available upgrade from forge puppet? https://forge.puppet.com/modules/puppet/fail2ban

**Comment by Dan33l** [comment]
Closed by PR https://github.com/voxpupuli/puppet-fail2ban/pull/178 previously merged
