### ISSUE TITLE
Please add Debian 12 template

### ISSUE THREAD

**Issue by sid3windr** [voxpupuli/puppet-fail2ban#199]
## What are you seeing

Debian 12 does not currently have any template. Copying Debian 11's template seems to work fine, however.

## Output log

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/Debian/12/etc/fail2ban/jail.conf.epp'
```

**Comment by kenyon** [comment]
#197 does this.

**Comment by sid3windr** [comment]
Sorry, looked through the issues and not the PRs!

**Comment by janit42** [comment]
> #197 does this.

#197 seems to be approved but not merged and released so far. Would be great to get that.

**Comment by Dan33l** [comment]
Closed by PR https://github.com/voxpupuli/puppet-fail2ban/pull/197 previously merged
