### ISSUE TITLE
Add Ubuntu 24.04 template

### ISSUE THREAD

**Issue by apw1388** [voxpupuli/puppet-fail2ban#212]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.4.0
- Ruby: 3.2.3
- Distribution: Ubuntu 24.04
- Module version: latest

## How to reproduce (e.g Puppet code you use)
Apply basic class
## What are you seeing
Error message about missing template on Ubuntu 24.04
## Output log
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/Ubuntu/24.04/etc/fail2ban/jail.conf.epp'
## Any additional information you'd like to impart
It would be great if Ubuntu 24.04, the latest LTS version, would be supported by the module, too. If you create new servers you would like to do with the latest mayor release.

**Comment by Dan33l** [comment]
Closed by #215 previously merged
