### ISSUE TITLE
Add support for Debian 12.

### ISSUE THREAD

**Issue by wolfcicd** [voxpupuli/puppet-fail2ban#213]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby: 3.1
- Distribution: Debian
- Module version: latest (4.2)

## How to reproduce (e.g Puppet code you use)

Attempt to install on Debian 12 via puppet.

## What are you seeing

Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/Debian/12/etc/fail2ban/jail.conf.epp' (file: /etc/puppetlabs/code/environments/production/modules/fail2ban/manifests/init.pp, line: 51, column: 26) on node none.

**Comment by Dan33l** [comment]
Closed by PR #197  previously merged
