### ISSUE TITLE
Typo in variable name

### ISSUE THREAD

**Issue by pawilon** [voxpupuli/puppet-fail2ban#24]
Thank you for a very useful module. Unfortunately, my tests with strict variable checking are failing because there's a typo in puppet-fail2ban/manifests/jail.pp:12:

```
$maxretry                    = $fail2ban::maxtretry,
```

righthand side has an extra `t`, should be $fail2ban::maxretry

**Comment by dhoppe** [comment]
Hello @pawilon, 

could you please provide a pull request against the develop branch?

Thank you very much.

**Comment by davealden** [comment]
@dhoppe Any idea as to when you'll release this?  I'm dying to switch to this module.  :)

**Comment by fcanovai** [comment]
This typo is still present in the master version
