### ISSUE TITLE
Custom jail doesn't work on Debian Wheezy

### ISSUE THREAD

**Issue by thatgraemeguy** [voxpupuli/puppet-fail2ban#27]
The fail2ban::jail define attempts to create the custom jail in the file ${::fail2ban::params::config_dir_path}/jail.d/${name}.conf. The version of fail2ban that is available on Debian Wheezy is 0.8.6, whereas support for custom jails in the 'jail.d' subdirectory was only added with fail2ban 0.8.9.

The end result is that fail2ban::jail is not working on Debian Wheezy, because fail2ban uses the jail.local file rather than the newer jail.d subdirectory.

**Comment by cFire** [comment]
Actually in retrospect not entirely sure my PR will also fix this issue.

**Comment by thatgraemeguy** [comment]
Long-term support for Debian Wheezy ended in May 2018. Closing.
