### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by brentclark** [voxpupuli/puppet-fail2ban#36]
Good day
A management and a template for Debian Stretch is needed.

Kind Regards
Brent Clark

**Comment by rowanruseler** [comment]
My bad, just noticed Jschaeff already made a pull request related to this fix.

How ever, 3d69b5cca557007aee291cc5c6d4597361db857f
Does contain some settings also available within the Jessie jail.conf

**Comment by launtony** [comment]
+1 I need :)

**Comment by brentclark** [comment]
Yeah not to come across as ungrateful, but still, as mrsmn stated "its blocking for stretch users".

**Comment by mrsmn** [comment]
Hello @voxpupuli team,

is there any progress planned on this?

Cheers.

**Comment by bastelfreak** [comment]
@brentclark yes. this is currently being implemented and we will kick of a new release afterwards
