### ISSUE TITLE
SyntaxError on debian stretch epp template

### ISSUE THREAD

**Issue by aba-rechsteiner** [voxpupuli/puppet-fail2ban#84]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.3
- Distribution: Debian 9.5
- Module version: v2.3.0

## How to reproduce (e.g Puppet code you use)
    class { 'fail2ban':
      config_file_template => "fail2ban/${::lsbdistcodename}/etc/fail2ban/jail.conf.epp",
    }
## What are you seeing
Syntax error since v2.3.0

## Output log
Info: Using configured environment 'dev'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Internal Server Error: org.jruby.exceptions.RaiseException: (SyntaxError) /etc/puppetlabs/code/environments/production/modules/fail2ban/templates/stretch/etc/fail2ban/jail.conf.epp:232: syntax error, unexpected kIN
; _erbout.concat(( "ssh" **in** $fail2ban::jails ).to_s); _erbout.concat "\nport    = ssh\nlogpath = %(sshd_log)s\nbackend = %(sshd_backend)s\n\n\n[sshd-ddos]\n# This jail corresponds to the standard configuration in Fail2ban.\n# The mail-whois action send a notification e-mail with a whois request\n# in the body.\nenabled = "
                          ^
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ekohl** [comment]
You're probably using a too old version of extlib. It's trying to handle epp with erb. Extlib 2.3.0 or newer should properly handle this:
https://github.com/voxpupuli/puppet-fail2ban/blob/c4cf635c0c0576c9ecbac1061fbdda16298aeaf4/metadata.json#L11-L14

**Comment by aba-rechsteiner** [comment]
okay thx @ekohl
