### ISSUE TITLE
Allow use of custom_jails param passed to in main class

### ISSUE THREAD

**Issue by kobybr** [voxpupuli/puppet-fail2ban#99]
$::fail2ban::custom_jails parameter is not being referenced in class fail2ban::config; Instead it is performing a hiera lookup

https://github.com/voxpupuli/puppet-fail2ban/blob/e082a9fb1b02c98bd02b8e4c5f0173737ee79d38/manifests/config.pp#L5

**Comment by bastelfreak** [comment]
Hi @kobybr. I think we can close the issue now, since #100 got merged?
